### PR TITLE
Make installation process simpler

### PR DESCRIPTION
**Pull request by firefly-cpp**
- switched from distutils to setuptools
- added README for CEC 2021 (we can add READMEs also for the other packages)
- added "make" command for dependency management

### CODE REVIEW

**Review by zStupan — COMMENTED** [review]
it would probably be better if instead of make setup, we instruct users to create a virtual environment and install the requirements like this: 
```sh
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```
In that case, requirements.txt should be moved to the NiaPy-examples/CEC directory. Then you could just `cd` to cec20* and run make build etc..

**Comment by firefly-cpp** [comment]
Good point!

**Comment by firefly-cpp** [comment]
You can modify my PR.

**Comment by zStupan** [comment]
@firefly-cpp How do I modify the PR?

**Comment by firefly-cpp** [comment]
In fact, I am going to merge this PR. You can submit then a fresh PR. Thanks.

**Pull request merged**
